name: Swift

on: [push, pull_request]
        

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Scout
    - name: Run tests
      run: xcodebuild test -scheme Scout